### ISSUE TITLE
Exception thrown when any settings are set

### ISSUE THREAD

**Issue by brijeshbharadwaj** [stirno/FluentAutomation#108]
When  MinimizeAllWindowsOnTestStart is set to true, tests crash on startup with the following exception.

Update: This seems to be occurring irrespective of what settings i try to configure.

Result Message: 
Test method UIAutomatedTests.UnitTest1.TestMethod1 threw exception: 
TinyIoC.TinyIoCResolutionException: Unable to resolve type: FluentAutomation.ActionSyntaxProvider ---> TinyIoC.TinyIoCResolutionException: Unable to resolve type: FluentAutomation.Interfaces.ICommandProvider
Result StackTrace:  
at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
 --- End of inner exception stack trace ---
    at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
   at TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at TinyIoC.TinyIoCContainer.Resolve(Type resolveType)
   at TinyIoC.TinyIoCContainer.Resolve[ResolveType]()
   at FluentAutomation.FluentSession.GetSyntaxProvider()
   at FluentAutomation.FluentTest.get_I()
   at FluentAutomation.PageObject`1.get_I()
   at FluentAutomation.PageObject`1.Go(String url)
   at FluentAutomation.PageObject`1.Go(Uri uri)
   at FluentAutomation.PageObject`1.Go()
   at UIAutomatedTests.UnitTest1.TestMethod1()

**Comment by stirno** [comment]
This error occurs when you try to access the `I` property without having Bootstrapped the provider first.

**Comment by brijeshbharadwaj** [comment]
Is this is same problem as this.provider not being available until I.Open is called?

Because my current code is 

```
        SeleniumWebDriver.Bootstrap(new []{SeleniumWebDriver.Browser.Firefox });
        Config.Configure(new FluentSettings()
                         {
                             ScreenshotPath = "D:\\UITestScreenies",
                             ScreenshotOnFailedAction = true,
                             MinimizeAllWindowsOnTestStart = true
                         });
```

And this is crashing in 3.0 beta.

**Comment by stirno** [comment]
Yes, the issue is the same. The reason you encounter it is that the FluentSettings object contains the 'result' of calling `Bootstrap` in a property called `ContainerRegistration`.

You have a few options, call `Config.Configure` before calling `Bootstrap` or use the new fluent configuration syntax which is much less scorched earth than replacing the Settings object:

```
Config
    .ScreenshotPath("D:\\UITestScreenies")
    .ScreenshotOnFailedAction(true)
    .MinimizeAllWindowsOnTestStart(true);
```
