### ISSUE TITLE
I.Expect.Alert()

### ISSUE THREAD

**Issue by stirno** [stirno/FluentAutomation#40]
Not working properly in Selenium using Firefox or Chrome drivers. Tracking so I can tackle this later.

System.NullReferenceException: Object reference not set to an instance of an object.
    at FluentAutomation.SeleniumWebDriver.AutomationProvider.HandleAlertDialog(String expectedMessage)
    at FluentAutomation.API.ExpectManager.Alert(String alertMessage)

**Comment by stirno** [comment]
Resolved.. although one important change was required... Users need to NOT use ClickMode.NoWait with dialogs as they are now auto-closed with their data tracked. A no-wait potentially causes the Expect to trigger before the alert has been handled.

Tagging this as need to document
